const ActionTypes = {
  // General
  SHOW_ALERT: 'SHOW_ALERT',
  HIDE_ALERT: 'HIDE_ALERT',
  SHOW_LOADING: 'SHOW_LOADING',
  HIDE_LOADING: 'HIDE_LOADING',

  // User
  USER_DATA: 'USER_DATA',
  GET_INDUSTRIES: 'GET_INDUSTRIES',
  LOGOUT: 'LOGOUT',
  IS_LOGIN: 'IS_LOGIN',


}

export default ActionTypes;
